from collections import Counter

# Input the space-separated NFL team votes as a single string
votes_input = input("Enter the NFL team votes (space-separated): ")

# Split the input string into a list of votes
votes = votes_input.split()

# Count the occurrences of each team vote
team_vote_counts = Counter(votes)

# Output the team names and their vote counts
for team, count in team_vote_counts.items():
    print(f'Team: {team}, Votes: {count}')
    
    CHIEFS	CHIEFS	LIONS	CHIEFS	CHIEFS	CHIEFS	CHIEFS	CHIEFS	CHIEFS	CHIEFS	LIONS	CHIEFS	CHIEFS	CHIEFS
    FALCONS	FALCONS	FALCONS	FALCONS	FALCONS	FALCONS	FALCONS	FALCONS	FALCONS	FALCONS	PANTHERS	FALCONS	FALCONS	FALCONS
    RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS	RAVENS
    BENGALS	BENGALS	BENGALS	BENGALS BENGALS	BROWNS	BENGALS	BENGALS	BENGALS	BROWNS	BENGALS	BENGALS	BENGALS	BROWNS
    JAGUARS	JAGUARS	JAGUARS	JAGUARS	JAGUARS	COLTS	JAGUARS	JAGUARS	COLTS	JAGUARS	JAGUARS	JAGUARS	JAGUARS	COLTS
    VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	VIKINGS	BUCCANEERS	VIKINGS	VIKINGS
    TITANS	SAINTS	TITANS	SAINTS	SAINTS	SAINTS	SAINTS	TITANS	TITANS	SAINTS	SAINTS	SAINTS	SAINTS	SAINTS
    49ERS	STEELERS	49ERS	49ERS 49ERS	49ERS	49ERS	49ERS	49ERS	49ERS	49ERS	49ERS	49ERS	49ERS
    COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS	COMMANDERS
    PACKERS	BEARS	BEARS	BEARS	BEARS	BEARS	PACKERS	BEARS	PACKERS	BEARS	BEARS	BEARS	BEARS	PACKERS
    BRONCOS	BRONCOS	BRONCOS	BRONCOS	BRONCOS	RAIDERS	BRONCOS	BRONCOS	RAIDERS	RAIDERS	BRONCOS	BRONCOS	RAIDERS	BRONCOS
    CHARGERS	DOLPHINS	CHARGERS	DOLPHINS	CHARGERS	DOLPHINS	CHARGERS	DOLPHINS	DOLPHINS	DOLPHINS	CHARGERS	CHARGERS	CHARGERS	DOLPHINS
    EAGLES	EAGLES	EAGLES	EAGLES	EAGLES	EAGLES	EAGLES	EAGLES	PATRIOTS	EAGLES	EAGLES	EAGLES	EAGLES	EAGLES
    SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS	RAMS	SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS	SEAHAWKS
    COWBOYS	COWBOYS	GIANTS	COWBOYS	COWBOYS	COWBOYS	COWBOYS	COWBOYS	COWBOYS	GIANTS	COWBOYS	COWBOYS	COWBOYS	COWBOYS
    BILLS	JETS	BILLS	JETS	BILLS	BILLS	JETS	BILLS	BILLS	BILLS	BILLS	BILLS	BILLS	BILLS
    